// <auto-generated/>
namespace WebUI.Areas.Identity.Pages.Account
{
    using Microsoft.AspNetCore.Mvc.RazorPages;

    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}
